export const DETAIL_REFRESH_QUEUE_INTERACTIVE_PRIORITY = 100;
export const DETAIL_REFRESH_QUEUE_BACKGROUND_PRIORITY = 40;
export const DETAIL_REFRESH_QUEUE_BUSY_RETRY_MS = 15_000;
export const DETAIL_REFRESH_QUEUE_FALLBACK_NEXT_REFRESH_MS = 30 * 24 * 60 * 60_000;
